/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_jnitest_JNITest */

#ifndef _Included_com_jni_jnitest_JNITest
#define _Included_com_jni_jnitest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_jnitest_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_jnitest_JNITest_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_jnitest_JNITest
 * Method:    isEquals
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_jnitest_JNITest_isEquals
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
